# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lozprofile', '0002_profilepro_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepart',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lozapp.Address'),
        ),
    ]
