# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('cp', models.IntegerField()),
                ('gps_x', models.IntegerField()),
                ('gps_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('date', models.DateTimeField()),
                ('place', models.CharField(max_length=45)),
                ('descriptive', models.TextField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lozapp.Categorie')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lozapp.City')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lozapp.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lozapp.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('adress', models.CharField(max_length=70)),
                ('siret', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Validation_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('validation_event', models.BooleanField(default=False)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lozapp.Administrator')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lozapp.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Validation_pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('validation_siret', models.BooleanField(default=False)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lozapp.Administrator')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lozapp.Pro')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lozapp.Pro'),
        ),
    ]
