# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lozprofile', '0001_initial'),
        ('lozapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lozprofile.ProfilePro'),
        ),
    ]
