# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 09:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lozapp', '0003_remove_address_poly'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='poly',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
