# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lozapp', '0004_auto_20160616_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='photo',
            field=models.ImageField(null=True, upload_to='categories'),
        ),
    ]
