# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lozapp', '0005_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default='2012-09-04 06:00:00.000000'),
            preserve_default=False,
        ),
    ]
